import source from "./mw900.json" with { type: "json" };
import type { ModuleDefinition } from "./types.ts";

// Generated by Blender. Do not hand-edit measured geometry or duplicate dimensions in UI.
export const MW900 = source as unknown as ModuleDefinition;
export const FACES = ["north", "south", "east", "west", "above", "below"] as const;
export const FACE_LABELS = {
  north: "Norte",
  south: "Sur",
  east: "Este",
  west: "Oeste",
  above: "Superior",
  below: "Inferior",
};
export const MATERIALS = {
  "panel-light": { label: "Panel claro", color: "#c9ccc6" },
  "panel-graphite": { label: "Panel grafito", color: "#454c50" },
  "floor-oak": { label: "Roble", color: "#aa9373" },
  "floor-concrete": { label: "Cemento", color: "#929693" },
};
